name: xuxemons

services:

  # =====================
  # MYSQL
  # =====================
  mysql:
    image: mysql:latest
    container_name: xuxemons_mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - xuxemons-network

  # =====================
  # LARAVEL
  # =====================
  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: xuxemons_laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./xuxemons-backend:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - xuxemons-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:${BACKEND_PORT}
    command: >
      bash -c "
      composer install --no-interaction --optimize-autoloader &&
      [ ! -f /var/www/html/.env ] && cp /var/www/html/.env.example /var/www/html/.env || true &&
      php artisan key:generate --no-interaction &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan migrate --force &&
      echo 'Server started' &&
      apache2-foreground
      "

  # =====================
  # ANGULAR
  # =====================
  frontend:
    image: node:latest
    container_name: xuxemons_angular_app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./xuxemons-frontend:/app
    ports:
      - "${FRONTEND_PORT}:4200"
    command: >
      sh -c "
      npm install &&
      npm start -- --host 0.0.0.0 --poll 2000
      "
    depends_on:
      - backend
    networks:
      - xuxemons-network

volumes:
  mysql_data:
 
networks:
  xuxemons-network:
    driver: bridge
